# -*- coding: utf-8 -*-
"""Feedback Logger Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u30J_7VeB3qGtlQUiNRcCW-jNnl5JHBo
"""

import json
import os
import logging
import threading
from datetime import datetime
from typing import Optional

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Resolve to the project's streamlit_app folder so logs are stored in the same place the UI reads from.
CURRENT_FILE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_FILE_DIR, '..'))
STREAMLIT_APP_DIR = os.path.join(PROJECT_ROOT, 'streamlit_app')
FEEDBACK_FILE = os.path.join(STREAMLIT_APP_DIR, 'feedback_log.json')
# Use a lock to prevent race conditions when writing to the JSON file
file_lock = threading.Lock()

def log_feedback(user_id: str, query: str, rating: int, comments: str) -> None:
    """
    Saves user feedback to a local JSON file and logs it to user activity.

    Args:
        user_id: A unique identifier for the user.
        query: The user's query that led to the feedback.
        rating: An integer rating (e.g., 1-5).
        comments: Optional user comments.
    """
    feedback_entry = {
        'timestamp': datetime.now().isoformat(),
        'user_id': user_id,
        'query': query,
        'rating': rating,
        'comments': comments
    }

    with file_lock:
        try:
            # Try to read existing data
            if os.path.exists(FEEDBACK_FILE):
                with open(FEEDBACK_FILE, 'r', encoding='utf-8') as f:
                    try:
                        data = json.load(f)
                        if not isinstance(data, list):
                            data = []
                    except json.JSONDecodeError:
                        data = []
            else:
                data = []

            # Append new entry
            data.append(feedback_entry)

            # Ensure directory exists and write data back
            os.makedirs(os.path.dirname(FEEDBACK_FILE), exist_ok=True)
            with open(FEEDBACK_FILE, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=4)
            logger.info(f"Successfully logged feedback for user {user_id}")
            
            # Also log to user activity if the module is available
            try:
                import sys
                import os as os_module
                backend_dir = os_module.path.abspath(os_module.path.join(os_module.path.dirname(__file__), '..'))
                if backend_dir not in sys.path:
                    sys.path.append(backend_dir)
                
                from backend.user_management_module import log_user_activity
                log_user_activity(
                    user_id=user_id,
                    activity_type='feedback',
                    query=query,
                    rating=rating,
                    comments=comments
                )
            except Exception as e:
                logger.warning(f"Could not log to user activity: {e}")

        except (IOError, OSError) as e:
            logger.error(f"Failed to write feedback to {FEEDBACK_FILE}: {e}")
        except Exception as e:
            logger.error(f"An unexpected error occurred in log_feedback: {e}")
